"""add email to person

Revision ID: ead8d1acd621
Revises: bdf08e103c6b
Create Date: 2026-02-24 03:13:37.644504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead8d1acd621'
down_revision: Union[str, Sequence[str], None] = 'bdf08e103c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###
     # Backfill existing rows so NOT NULL will not fail
    op.execute(
        "UPDATE people SET email = 'placeholder@example.com' WHERE email IS NULL"
    )

    # SQLite-safe alter via batch mode
    with op.batch_alter_table('people') as batch_op:
        batch_op.alter_column('email', nullable=False)



def downgrade():
    # allow SQLite-safe operations
    with op.batch_alter_table('people') as batch_op:
        batch_op.alter_column('email', nullable=True)
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'email')
    # ### end Alembic commands ###
